name: 'Go Coverage'
description: 'Generates Go coverage reports without third party services'
inputs:
  token:
    description: github token
    default:  ${{ github.token }}
  report-url:
    description: URL of final uploaded report.  e.g. https://reports.example.com/{{ $github.sha }}/cover.html
    required: false
  working-directory:
    description: 'Working directory.  defaults to project root'
    required: false
    default: ''
  report-filename:
    description: 'File or pathname for the resulting html coverage report'
    required: false
    default: 'go-coverage.html'
  cover-mode:
    description: 'Parameter to pass to go tests -covermode argument.  Either count, set or atomic'
    default: 'count'
  cover-pkg:
    description: 'Parameter to pass to go tests -coverpkg argument. Leave empty to omit flag'
    default: ''
  test-args:
    description: 'Build arguments to pass to go test'
    default: '[]'
    required: false
  coverage-threshold:
    description: 'Fail the build if the coverage drops below supplied percentage'
    required: false
    default: 0
  fail-coverage:
    description: 'Fail the build if coverage drops below coverage-threshold.  One of "always", "never" or "only_pull_requests"'
    required: false
    default: only_pull_requests
  add-comment:
    description: 'Adds a comment to the PR with coverage information if true. If false will only add an action summary report'
    required: false
    default: true
  ignore-pattern:
    description: 'One or more regular expressions matching filenames to exclude from coverage statistics (e.g. for generated Go files)'
    required: false
    default: ''
  notes-ref:
    description: 'The refname to use for the git notes. Defaults to gocoverage'
    required: false
    default: gocoverage

outputs:
  report-pathname:
    description: 'The full pathname of the generated coverage report'
  gocov-pathname:
    description: 'The full pathname of the raw .cov coverage data'
  gocov-agg-pathname:
    description: 'The full pathname of the aggregated .cov coverage data'
  coverage-pct:
    description: 'The coverage figure for the whole project.  e.g "83.4"'
  meets-threshold:
    description: 'Set to true if the current coverage is greater than coverage-threshold'
  coverage-last-pct:
    description: 'The prior coverage percentage'
  coverage-last-sha:
    description: 'Commit sha prior coverage was recorded at'
  coverage-delta:
    description: 'Amount coverage has changed'
  package-count:
    description: 'Number of Go packages scanned'
  uncovered-packages:
    description: 'Number of Go packages with no test coverage'
runs:
  using: 'node20'
  main: 'dist/index.js'
